### ISSUE TITLE
idea: helper for ContainsAll / ContainsEvery

### ISSUE THREAD

**Issue by shoenig** [shoenig/test#105]
for slices of Contains compatible things, it would be nice to have helpers for comparing against another slice of elements

**Comment by jan-xyz** [comment]
Would `SameElements` be maybe a good name for the function?

**Comment by shoenig** [comment]
It's been so long now I'm trying to remember what this was about 😅. We already have `SliceContainsAll` (same number of elements, any order) and `SliceContainsSubset` (subset of elements, any order) and of course `Eq` (same number of elements, same order). 

It was probably for data-structures that implement [ContainsFunc](https://github.com/shoenig/test/blob/main/interfaces/interfaces.go#L92-L95); particularly like in [go-set](https://github.com/hashicorp/go-set/blob/main/collection.go#L48-L49).

For the `ContainsFunc` interface we already have [ContainsSubset](https://github.com/shoenig/test/blob/main/test.go#L785-L790), but nothing like the `SliceContainsAll` (subset of elements) analogue. So yeah, that's probably what I was thinking.

In which case we need to cover the case of elements matching, while asserting the same number of elements. Since we already have `SliceContainsAll`, to be consistent probably the best analogous name would just be `ContainsAll`. 

No doubt though, `*SameElements` would have been be more clear than `*All`, or perhaps `*SameItems` to be just a bit shorter. It's probably worth adding those variants and then deprecating the `*All` naming, and publishing as `v1.8.0`.

Sorry for taking so long to respond @jan-xyz! Any chance you'd be interested in opening a PR for making those changes? Of course it's fine if not ~
