### ISSUE TITLE
FileNotExist does not work

### ISSUE THREAD

**Issue by shoenig** [shoenig/test#118]
`FileNotExist` does not work as expected, due to misusing the `fs` package, which does not expect absolute paths. When you do, you get invalid argument error.

**Comment by alessio-perugini** [comment]
:wave: Hi there, do you mind if I'll work on this?

**Comment by shoenig** [comment]
Go for it, @alessio-perugini !

@gulducat and I looked into this briefly - I suspect `FileNotExists` just needs to trim any leading `/`, similar to what `FileExists` is already doing. There might also be room to improve the test cases around this little family of functions to make sure something like this isn't missed again.
