### ISSUE TITLE
Add a CI via GitHub actions

### ISSUE THREAD

**Issue by ccoVeille** [shoenig/test#159]
**Is your feature request related to a problem? Please describe.**
I pushed changes with https://github.com/shoenig/test/pull/158 and I forgot to launch the tests
There was no CI to catch it.

We shouldn't be able to push code that could be merged without being tested.

**Describe the solution you'd like**
please add a GitHub action to launch the test to validate incoming PRs

**Comment by shoenig** [comment]
Ah, we do already have https://github.com/shoenig/test/blob/main/.github/workflows/ci.yaml
but it's configured to run on `push` - it should also be configured to run on `pull_request`.
